//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibloteka.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bibloteka.Lang.langRes", typeof(langRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librat.
        /// </summary>
        internal static string btnBooks {
            get {
                return ResourceManager.GetString("btnBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faqja kryesore.
        /// </summary>
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huazimet.
        /// </summary>
        internal static string btnLoans {
            get {
                return ResourceManager.GetString("btnLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçu.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkyçu.
        /// </summary>
        internal static string btnLogOut {
            get {
                return ResourceManager.GetString("btnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili im.
        /// </summary>
        internal static string btnMyProfile {
            get {
                return ResourceManager.GetString("btnMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexuesit.
        /// </summary>
        internal static string btnReaders {
            get {
                return ResourceManager.GetString("btnReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stafi.
        /// </summary>
        internal static string btnStaff {
            get {
                return ResourceManager.GetString("btnStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librat Total.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informata te pergjithshme.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librat e huazuar.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librat e kthyer.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anetaret Total.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexuesit.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stafi.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemi për menaxhimin e biblotekës.
        /// </summary>
        internal static string lblBibloteka {
            get {
                return ResourceManager.GetString("lblBibloteka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçja ne sistem.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anetaret.
        /// </summary>
        internal static string lblMembers {
            get {
                return ResourceManager.GetString("lblMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librat.
        /// </summary>
        internal static string lblReports {
            get {
                return ResourceManager.GetString("lblReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nofka.
        /// </summary>
        internal static string txtUsername {
            get {
                return ResourceManager.GetString("txtUsername", resourceCulture);
            }
        }
    }
}
